spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':   # Appliquer à toutes les routes
            allowed-origins: "http://localhost:4200"  # Frontend Angular
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allow-credentials: true  # Permet l'envoi des cookies
